variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  # we use the docker image to have all the dependencies installed
  image: 
      name: registry.gitlab.com/panoramax/server/sgblur
      entrypoint: [""]
  script:
    - pip install --editable ".[dev]"
    - pytest -vv

