[project]
name = "sgblur"
description = "Blurring API"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]

dependencies = [
    "ultralytics==8.4.7",
    "pyturbojpeg==1.8.2",
    "Pillow==12.1.0",
    "uuid==1.30",
    "exifread==3.5.1",
    "python-multipart==0.0.21",
    "fastapi==0.128.0",
    "uvicorn==0.40.0",
    "requests==2.32.5",
    "piexif==1.1.3",
    "pydantic-settings==2.12.0",
    "pydantic==2.12.5",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "httpx>=0.28.1",
    "ruff>=0.11.3",
    "requests-mock>=1.12.1",
    "multipart>=1.2.1",
]

[tool.ruff]
line-length = 140
